apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-booking-deployment
  labels:
    app: ticket-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-booking
  template:
    metadata:
      labels:
        app: ticket-booking
    spec:
      containers:
      - name: ticket-booking-container
        image: your-dockerhub-username/ticket-booking-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
